template_path: server.j2
stack_name: k3s-server

sceptre_user_data:
  ami: ami-0c9d48b5db609ad6e # amzn2-ami-hvm-2.0.2019.*x86_64-gp2
  instance_type: t3.small
  time_zone: {{ var.time_zone }}
  domain_name: {{ var.domain_name }}
